CREATE
OR REPLACE WAREHOUSE MY_WAREHOUSE WITH WAREHOUSE_SIZE = MEDIUM AUTO_SUSPEND = 300 SCALING_POLICY = 'ECONOMY' MIN_CLUSTER_COUNT = 1 MAX_CLUSTER_COUNT = 3 INITIALLY_SUSPENDED = TRUE;
DROP WAREHOUSE MY_WAREHOUSE;