CREATE DATABASE EXERCISE_DB;
CREATE
OR REPLACE STAGE EXERCISE_DB.PUBLIC.JSON_STAGE url = 's3://snowflake-assignments-mc/unstructureddata/';
CREATE
OR REPLACE file format EXERCISE_DB.PUBLIC.FILE_FORMAT TYPE = 'JSON';
CREATE
OR REPLACE TABLE EXERCISE_DB.PUBLIC.JSON_RAW (raw variant);
COPY INTO EXERCISE_DB.PUBLIC.JSON_RAW
FROM
    @EXERCISE_DB.PUBLIC.JSON_STAGE file_format = EXERCISE_DB.PUBLIC.FILE_FORMAT;
SELECT
    *
FROM
    EXERCISE_DB.PUBLIC.JSON_RAW
LIMIT
    1;
DROP DATABASE EXERCISE_DB;